#!/usr/bin/env node
// 03_enrich.cjs — 机械补全
// 读 AI 产出的 book.json，自动生成拼音/分词/id/dict(拼音+英文)/例句拼音，
// 输出 book.enriched.json。仅做可机械推导的字段；英文释义、词性、例句英文由 AI 提供。
const fs = require('fs')
const path = require('path')
const { pinyin, segment } = require('pinyin-pro')

const BOOKS = path.join(__dirname, 'books')
const bookId = process.argv[2]
if (!bookId) { console.error('用法: node 03_enrich.cjs <bookId>'); process.exit(1) }

const bookPath = path.join(BOOKS, bookId, 'book.json')
if (!fs.existsSync(bookPath)) { console.error('找不到', bookPath, '\n请先完成读图步骤生成 book.json'); process.exit(1) }

const book = JSON.parse(fs.readFileSync(bookPath, 'utf-8'))
const code = (book.bookCode || bookId.replace(/[^a-z0-9]/gi, '').toLowerCase())

const isPunct = (t) => /^[\s\p{P}\p{S}]+$/u.test(t)
function segWords(cn) {
  try {
    const segs = segment(cn || '')
    // pinyin-pro v3 segment 返回 [{origin,result}, ...]
    const toks = (segs.length && typeof segs[0] === 'object') ? segs.map((s) => s.origin) : segs
    return toks.filter((t) => typeof t === 'string' && !isPunct(t))
  } catch { return String(cn || '').split('') }
}
function py(s) {
  try {
    const arr = pinyin(s || '', { toneType: 'symbol', type: 'array' })
    return arr.filter((t) => !/^[\p{P}\p{S}\s]+$/u.test(t)).join(' ')
  } catch { return String(s || '') }
}
// 贪心最长匹配分词：优先把生字表/常用词表里的多字词条保持为一整词（如 田芳、哪儿、同学），
// 避免 pinyin-pro segment 把名字/词拆成单字。dictKeys 需按长度降序传入。
function tokenize(cn, dictKeys) {
  const toks = []
  const s = String(cn || '')
  let i = 0
  while (i < s.length) {
    const ch = s[i]
    if (isPunct(ch)) { i++; continue }
    let matched = ''
    for (const k of dictKeys) {
      if (k && s.startsWith(k, i)) { matched = k; break }
    }
    if (matched) { toks.push(matched); i += matched.length }
    else { toks.push(ch); i++ }
  }
  return toks
}
function cap(s) { return s ? s.charAt(0).toUpperCase() + s.slice(1) : s }

// 英文释义查找：先精确匹配，再子串回退（处理 AI 给的 dict 键与分词粒度不一致）
function lookupEnglish(word, aiDict) {
  if (!aiDict || typeof aiDict !== 'object') return ''
  if (aiDict[word] != null && aiDict[word] !== '') return aiDict[word]
  for (const k of Object.keys(aiDict)) {
    if (!k) continue
    if (word.includes(k) || k.includes(word)) return aiDict[k]
  }
  return ''
}

// 常用词英义表（兜底）：当 book.json 的句子未显式提供 dict，且不在本课生词表时，
// 用此表自动补全逐词英文释义，避免逐个句子手写 dict。可按需扩充。
const COMMON = {
  "北京语言大学": "Beijing Language and Culture University",
  "过一会儿": "after a while; in a bit",
  "电话号码": "phone number",
  "手机号码": "mobile phone number",
  "中国学生": "Chinese student",
  "一本词典": "",
  "马马虎虎": "so-so",
  "外贸公司": "foreign trade company",
  "汉英词典": "Chinese-English dictionary",
  "聊聊天儿": "to chat a bit",
  "中国画儿": "Chinese painting",
  "和平公园": "Heping Park",
  "人民广场": "People's Square",
  "什么时候": "when",
  "四点多": "a little past four o'clock",
  "打电话": "to make a phone call",
  "对不起": "sorry",
  "踢足球": "to play football",
  "留学生": "international student",
  "代表队": "representative team",
  "托福班": "TOEFL class",
  "是不是": "whether or not; yes or no",
  "没有呢": "not yet",
  "图书馆": "library",
  "嗓子疼": "sore throat",
  "肚子疼": "stomachache",
  "拉肚子": "to have diarrhea",
  "星期二": "Tuesday",
  "天安门": "Tian'anmen",
  "没关系": "it doesn't matter",
  "王老师": "Teacher Wang",
  "中国人": "Chinese person",
  "美国人": "American",
  "鸡蛋汤": "egg soup",
  "十六块": "sixteen yuan",
  "三十四": "thirty-four",
  "人民币": "RMB",
  "一会儿": "a while",
  "办公室": "office",
  "十八楼": "18th building",
  "房间号": "room number",
  "一下儿": "a bit",
  "王教授": "Professor Wang",
  "马校长": "Principal Ma",
  "他们俩": "the two of them",
  "韩国人": "Korean",
  "没什么": "it's nothing",
  "怎么样": "how about",
  "新同学": "new classmate",
  "林老师": "Teacher Lin",
  "日用品": "daily necessities",
  "一本书": "",
  "关经理": "Manager Guan",
  "有点儿": "a bit",
  "五口人": "",
  "有没有": "do you have",
  "一百多": "one hundred plus",
  "有时候": "sometimes",
  "电视剧": "TV drama",
  "星期六": "Saturday",
  "星期日": "Sunday",
  "综合课": "comprehensive course",
  "口语课": "oral course",
  "听力课": "listening course",
  "阅读课": "reading course",
  "文化课": "culture course",
  "体育课": "PE course",
  "曲别针": "paper clip",
  "代表团": "delegation",
  "羽绒服": "down jacket",
  "一点儿": "a little bit",
  "七百二": "seven hundred twenty",
  "二十二": "twenty-two",
  "上上网": "",
  "十一点": "eleven o'clock",
  "同学们": "classmates",
  "一年级": "first year",
  "足球场": "soccer field",
  "博物馆": "museum",
  "七八百": "seven or eight hundred",
  "红绿灯": "traffic light",
  "太极拳": "tai chi",
  "星期一": "Monday",
  "一三五": "one-three-five (Mon-Wed-Fri)",
  "星期三": "Wednesday",
  "星期五": "Friday",
  "电视台": "TV station",
  "为什么": "why",
  "不客气": "you're welcome",
  "李老师": "Teacher Li",
  "看电影": "to watch a movie",
  "分钟后": "after (X) minutes",
  "出租车": "taxi",
  "田芳": "Tian Fang (name)",
  "张东": "Zhang Dong (name)",
  "阿姨": "aunt (polite term for older woman)",
  "哪儿": "where",
  "同学": "classmate",
  "一个": "one (a)",
  "中学": "middle school",
  "出国": "to go abroad",
  "什么": "what",
  "时候": "time; moment",
  "回来": "come back",
  "手机": "mobile phone",
  "可是": "but; however",
  "关机": "to turn off (one's phone)",
  "是吗": "is that so?",
  "对了": "by the way",
  "开机": "to turn on (one's phone)",
  "电话": "telephone; phone",
  "下午": "afternoon",
  "怎么": "how; why",
  "今天": "today",
  "我们": "we; us",
  "比赛": "match; game; to compete",
  "你们": "you (plural)",
  "没有": "not have; haven't",
  "这次": "this time",
  "祝贺": "to congratulate",
  "事儿": "thing; matter",
  "报名": "to register; to sign up",
  "已经": "already",
  "明天": "tomorrow",
  "一起": "together",
  "好的": "OK; all right",
  "吃饭": "to eat (a meal)",
  "昨天": "yesterday",
  "晚上": "evening",
  "早饭": "breakfast",
  "午饭": "lunch",
  "晚饭": "dinner",
  "啤酒": "beer",
  "一些": "some; a few",
  "因为": "because",
  "所以": "therefore",
  "但是": "but; however",
  "然后": "then; afterwards",
  "接着": "then; next",
  "后来": "afterwards; later",
  "首先": "first; first of all",
  "最后": "finally; last",
  "其实": "actually; in fact",
  "不过": "but; however",
  "而且": "and; moreover",
  "虽然": "although",
  "于是": "thereupon; as a result",
  "可以": "can; may; OK",
  "感到": "feel",
  "常常": "often; frequently",
  "寂寞": "lonely",
  "难过": "sad; upset",
  "厉害": "serious; severe",
  "心情": "mood; state of mind",
  "宿舍": "dormitory; dorm room",
  "教室": "classroom",
  "食堂": "cafeteria; canteen",
  "礼堂": "auditorium",
  "操场": "playground; sports field",
  "医院": "hospital",
  "医生": "doctor",
  "护士": "nurse",
  "病人": "patient",
  "大夫": "doctor (informal)",
  "药品": "medicine",
  "药店": "pharmacy",
  "身体": "body; health",
  "生病": "fall ill",
  "检查": "examination; to examine",
  "发烧": "to have a fever",
  "感冒": "to catch a cold",
  "咳嗽": "to cough",
  "头疼": "headache",
  "头痛": "headache",
  "嗓子": "throat",
  "肚子": "belly; stomach",
  "大便": "stool; bowel movement",
  "小便": "urine; to urinate",
  "化验": "laboratory test",
  "结果": "result",
  "肠炎": "enteritis",
  "消化": "digestion; to digest",
  "牛肉": "beef",
  "鱼肉": "fish (meat)",
  "鸡肉": "chicken",
  "猪肉": "pork",
  "面包": "bread",
  "牛奶": "milk",
  "咖啡": "coffee",
  "果汁": "fruit juice",
  "可乐": "Coke",
  "瓶子": "bottle",
  "杯子": "cup",
  "筷子": "chopsticks",
  "姐姐": "older sister",
  "弟弟": "younger brother",
  "哥哥": "older brother",
  "妹妹": "younger sister",
  "爸爸": "father",
  "妈妈": "mother",
  "爷爷": "grandfather (paternal)",
  "奶奶": "grandmother (paternal)",
  "玛丽": "Mary (name)",
  "麦克": "Mike (name)",
  "大卫": "David (name)",
  "出来": "come out",
  "进去": "go in",
  "起来": "get up",
  "看见": "see; spot",
  "听到": "hear",
  "遇到": "meet; encounter",
  "找到": "find",
  "想到": "think of",
  "觉得": "feel; think",
  "知道": "know",
  "认识": "know; recognize",
  "了解": "understand",
  "相信": "believe",
  "希望": "hope; wish",
  "喜欢": "like; love",
  "担心": "worry about",
  "关心": "care about",
  "注意": "pay attention to",
  "开始": "start; begin",
  "结束": "end; finish",
  "继续": "continue",
  "准备": "prepare",
  "帮助": "help",
  "告诉": "tell",
  "回答": "answer",
  "或者": "or",
  "应该": "should",
  "愿意": "willing to",
  "需要": "need",
  "可能": "possible; maybe",
  "玩儿": "to have fun; to play",
  "托福": "TOEFL",
  "打针": "to give or have an injection",
  "舞会": "ball; dancing party",
  "跳舞": "to dance",
  "学习": "study; learn",
  "你好": "hello",
  "汉语": "Chinese language",
  "英语": "English",
  "北京": "Beijing",
  "邮局": "post office",
  "寄信": "mail a letter",
  "银行": "bank",
  "取钱": "withdraw money",
  "星期": "week, day of the week",
  "学校": "school",
  "再见": "goodbye",
  "谢谢": "thank you",
  "客气": "polite",
  "工作": "work",
  "请问": "excuse me, may I ask",
  "贵姓": "your surname (honorific)",
  "名字": "name",
  "哪国": "which country",
  "汉字": "Chinese characters",
  "发音": "pronunciation",
  "中文": "Chinese language",
  "老师": "teacher",
  "杂志": "magazine",
  "英文": "English language",
  "朋友": "friend",
  "中午": "noon",
  "馒头": "steamed bun",
  "米饭": "rice",
  "一碗": "a bowl of",
  "这些": "these",
  "饺子": "dumpling",
  "包子": "steamed stuffed bun",
  "面条": "noodles",
  "水果": "fruit",
  "苹果": "apple",
  "一斤": "one jin (half kilo)",
  "多少": "how much",
  "别的": "other",
  "橘子": "orange (fruit)",
  "两斤": "two jin",
  "一共": "altogether",
  "五十": "fifty",
  "换钱": "exchange money",
  "小姐": "miss",
  "二百": "two hundred",
  "美元": "US dollar",
  "先生": "sir",
  "数数": "count",
  "学生": "student",
  "一门": "Door 1",
  "介绍": "introduce",
  "欢迎": "welcome",
  "罗兰": "Luolan",
  "他们": "they",
  "语法": "grammar",
  "比较": "relatively",
  "容易": "easy",
  "同屋": "roommate",
  "哪个": "which",
  "箱子": "suitcase",
  "这儿": "here",
  "这个": "this one",
  "那个": "that one",
  "东西": "thing",
  "中药": "Chinese medicine",
  "茶叶": "tea leaves",
  "两件": "two (pieces)",
  "衣服": "clothes",
  "一把": "a (for objects with handle)",
  "雨伞": "umbrella",
  "一瓶": "a bottle of",
  "香水": "perfume",
  "还有": "also have",
  "两张": "two (for flat objects)",
  "光盘": "CD",
  "三支": "three (for pen-like objects)",
  "好久": "a long time",
  "最近": "recently",
  "开学": "start of school",
  "点儿": "a little",
  "还是": "or",
  "颜色": "color",
  "那儿": "there",
  "几口": "how many (for family members)",
  "全家": "whole family",
  "照片": "photo",
  "一张": "one (for flat objects)",
  "两个": "two",
  "一家": "a",
  "公司": "company",
  "经理": "manager",
  "商店": "store",
  "律师": "lawyer",
  "职员": "employee",
  "大概": "roughly, about",
  "中国": "Chinese",
  "外国": "foreign",
  "现在": "now",
  "咱们": "we (inclusive)",
  "上网": "to go online",
  "资料": "information, material",
  "安静": "quiet",
  "复习": "to review",
  "课文": "text",
  "预习": "to preview",
  "生词": "new word",
  "练习": "exercise",
  "天儿": "",
  "微信": "WeChat",
  "收发": "to send and receive",
  "邮件": "email",
  "也是": "me too",
  "电影": "movie",
  "休息": "to rest",
  "公园": "park",
  "超市": "supermarket",
  "正在": "in the process of",
  "音乐": "music",
  "录音": "recording",
  "书店": "bookstore",
  "学期": "semester",
  "听力": "listening",
  "阅读": "reading",
  "顺便": "conveniently, on the way",
  "读者": "Reader (magazine)",
  "不用": "no need",
  "上海": "Shanghai",
  "旅行": "travel",
  "外贸": "foreign trade",
  "参观": "to visit",
  "翻译": "interpreter, translator",
  "飞机": "airplane",
  "火车": "train",
  "问题": "problem",
  "光临": "to visit (polite)",
  "看看": "to take a look",
  "好看": "good-looking",
  "便宜": "cheap",
  "试试": "to try",
  "当然": "of course",
  "合适": "fitting, suitable",
  "九百": "nine hundred",
  "六百": "six hundred",
  "七百": "seven hundred",
  "大学": "university",
  "毕业": "to graduate",
  "明年": "next year",
  "后年": "the year after next",
  "今年": "this year",
  "多大": "how old",
  "生日": "birthday",
  "十月": "October",
  "十八": "eighteen",
  "正好": "happens to be",
  "打算": "to plan",
  "举行": "to hold (event)",
  "晚会": "evening party",
  "参加": "to participate",
  "时间": "time",
  "房间": "room",
  "一定": "definitely",
  "快乐": "happy",
  "每天": "every day",
  "早上": "morning",
  "起床": "to get up",
  "上课": "to have class",
  "上午": "morning",
  "十二": "twelve",
  "下课": "to finish class",
  "以后": "after",
  "口语": "spoken language",
  "锻炼": "to exercise",
  "听听": "to listen a bit",
  "睡觉": "to sleep",
  "爬山": "mountain climbing",
  "好了": "good",
  "出发": "to set off, depart",
  "集合": "to gather, assemble",
  "上车": "to board",
  "一刻": "quarter (of an hour)",
  "准时": "on time, punctually",
  "大家": "everyone",
  "谈谈": "to talk about",
  "自己": "oneself",
  "爱好": "hobby",
  "京剧": "Peking opera",
  "非常": "very",
  "电脑": "computer",
  "游戏": "game",
  "愉快": "happy, cheerful",
  "田中": "Tanaka (name)",
  "业余": "spare time",
  "以前": "before",
  "书法": "calligraphy",
  "特别": "especially",
  "兴趣": "",
  "高兴": "happy, glad",
  "里边": "inside",
  "东边": "east side",
  "西边": "west side",
  "地方": "place",
  "劳驾": "excuse me",
  "打听": "to ask about",
  "中间": "middle, between",
  "多远": "how far",
  "一直": "straight",
  "马路": "road",
  "白色": "white (color)",
  "不会": "cannot",
  "听说": "I heard that",
  "体育": "physical education",
  "不能": "cannot",
  "意思": "meaning",
  "小时": "hour",
  "舒服": "comfortable, well",
  "看病": "to see a doctor",
  "表演": "to perform",
  "节目": "program",
  "不好": "not good",
  "不错": "not bad, quite good",
  "进步": "progress",
  "水平": "level",
  "提高": "to improve",
  "哪里": "not at all (modest)",
  "不准": "inaccurate",
  "流利": "fluent",
  "这么": "so",
  "努力": "hardworking",
  "认真": "diligent, serious",
  "运动": "sport, exercise",
  "跑步": "to run, jogging",
  "篮球": "basketball",
  "刚才": "just now",
  "坚持": "to persist",
  "不谢": "don't thank",
  "李月": "Li Yue (name)",
  "不是": "not is",
  "美国": "America",
  "女儿": "daughter",
  "二十": "twenty",
  "好吃": "delicious",
  "看书": "to read",
  "小猫": "kitten",
  "小狗": "puppy",
  "椅子": "chair",
  "下面": "under",
  "儿子": "son",
  "不在": "not at",
  "桌子": "table/desk",
  "前面": "front",
  "王方": "Wang Fang (name)",
  "后面": "behind",
  "谢朋": "Xie Peng (name)",
  "天气": "weather",
  "下雨": "to rain",
  "不太": "not too",
  "没看": "didn't see",
  "电视": "TV",
  "她的": "her",
  "开车": "to drive",
  "四十": "forty",
  "漂亮": "pretty",
  "是啊": "yes (agreeing)",
  "不少": "quite a few",
  "没买": "didn't buy",
  "饭店": "hotel/restaurant",
  "是的": "yes",
  "喂": "hello",
  "是": "to be (am/is/are)",
  "吗": "(question particle)",
  "吧": "(particle, soft suggestion/guess)",
  "您": "you (polite)",
  "好": "good; well; OK",
  "去": "to go",
  "她": "she; her",
  "就": "just; simply",
  "家": "home; family",
  "了": "(particle: completed action / new situation)",
  "的": "(possessive/modifier particle)",
  "要": "want; need; will",
  "看": "to look; to see; to visit",
  "能": "can; able to",
  "没": "not (past)",
  "说": "to say; to speak",
  "你": "you",
  "打": "to hit; to make (a phone call)",
  "我": "I; me",
  "再": "again (future)",
  "啊": "(interjection)",
  "忘": "to forget",
  "快": "quick; hurry",
  "又": "again",
  "响": "to ring; to make a sound",
  "接": "to answer (a call); to receive",
  "给": "give; for",
  "做": "to do; to make",
  "跟": "with",
  "队": "team",
  "输": "to lose (a game)",
  "赢": "to win (a game)",
  "几": "how many; several",
  "比": "than; to compare",
  "二": "two",
  "一": "one",
  "有": "to have",
  "想": "want; think",
  "上": "to attend (a class)",
  "报": "to report; to register",
  "也": "also; too",
  "考": "to take a test",
  "陪": "to accompany",
  "饿": "hungry",
  "妈": "mom",
  "不": "not",
  "在": "to be at; (at)",
  "张": "Zhang (surname)",
  "东": "east",
  "个": "(measure word)",
  "回": "to return; to reply",
  "来": "to come",
  "还": "still; also",
  "他": "he; him",
  "找": "to look for",
  "问": "to ask",
  "让": "let; allow",
  "请": "please; invite",
  "叫": "call; name",
  "使": "make; cause",
  "把": "BA marker",
  "被": "passive marker",
  "从": "from",
  "向": "towards",
  "往": "towards",
  "对": "to; towards; correct",
  "为": "for",
  "和": "and; with",
  "都": "all; both",
  "太": "too; excessively",
  "更": "more",
  "最": "most",
  "真": "really; truly",
  "正": "just; right",
  "刚": "just now",
  "才": "only then; just",
  "先": "first",
  "只": "only",
  "很": "very",
  "挺": "quite; rather",
  "较": "relatively",
  "会": "can; will",
}

let totalSent = 0, totalWords = 0
for (let li = 0; li < book.lessons.length; li++) {
  const lesson = book.lessons[li]
  const lessonNum = lesson.lessonNum || (li + 1)
  lesson.lessonId = lesson.lessonId || `lesson${lessonNum}`

  // 本课生词英义表：句子 dict 的兜底来源之一（优先于 COMMON）
  const vocabEn = {}
  for (const w of (lesson.words || [])) { if (w && w.hanzi) vocabEn[w.hanzi] = w.english || '' }

  if (lesson.texts) {
    const segDict = Object.keys(vocabEn).concat(Object.keys(COMMON)).sort((a, b) => b.length - a.length)
    for (let ti = 0; ti < lesson.texts.length; ti++) {
      const text = lesson.texts[ti]
      const textId = `${code}-l${lessonNum}-t${ti + 1}`
      text.id = text.id || textId
      for (let si = 0; si < (text.sentences || []).length; si++) {
        const s = text.sentences[si]
        s.id = `${code}-l${lessonNum}-t${ti + 1}-s${si + 1}`
        // 优先用 AI 显式提供的 dict 键作为分词；否则用贪心最长匹配（生字表+常用词表）做逐词分词。
        const aiDict = s.dict || {}
        const words = Object.keys(aiDict).length ? Object.keys(aiDict) : tokenize(s.cn, segDict)
        s.split = words.join(' ')
        const dict = {}
        for (const w of words) {
          const en = aiDict[w] != null && aiDict[w] !== '' ? aiDict[w] : (vocabEn[w] || COMMON[w] || '')
          const p = py(w)
          dict[w] = en ? `${p} / ${en}` : p
        }
        s.dict = dict
        totalSent++
      }
    }
  }

  if (lesson.words) {
    for (let wi = 0; wi < lesson.words.length; wi++) {
      const w = lesson.words[wi]
      w.id = `${code}-l${lessonNum}-w${wi + 1}`
      w.pinyin = w.pinyin || py(w.hanzi)
      w.examplePinyin = cap(py(w.exampleCn))
      totalWords++
    }
  }
}

const outPath = path.join(BOOKS, bookId, 'book.enriched.json')
fs.writeFileSync(outPath, JSON.stringify(book, null, 2), 'utf-8')
console.log(`[enrich] 完成：${totalSent} 句 / ${totalWords} 词 → ${outPath}`)
